name: Publish changelog

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for the deployment'
        required: true
        type: string
      env:
        description: 'The environment to deploy to'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: 'The tag for the deployment'
        required: true
        type: string
      env:
        description: 'The environment to deploy to'
        required: true
        type: string

    secrets:
      example_secret:
        required: false
        description: 'An example secret, if needed.'

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Get tags
        run: git fetch --tags origin
      - name: Get previous release tag
        id: get_previous_release_tag
        run: |
          PREVIOUS_TAG=$(git tag --sort=creatordate | grep -P "v[0-9]+\.[0-9]+.[0-9]+$" | grep -v "${{ inputs.tag }}" | tail -n1)
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
      - name: Run custom action
        run: |
          echo "PREVIOUS_TAG: ${{ steps.get_previous_release_tag.outputs.PREVIOUS_TAG }}"
          echo "TAG: ${{ inputs.tag }}"
          echo "ENV: ${{ inputs.env }}"
