name: Create release

# This step triggers after the learner creates a new repository from the template
# This step sets STEP to 1
# This step closes <details id=0> and opens <details id=1>

# This will run every time we create push a commit to `main`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     main
  #   types:
  #     closed

permissions: write-all

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  get_pr_number:
    env:
      GH_TOKEN: ${{ github.token }}
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}    
      - name: Get tags
        run: |
          git fetch --tags origin
          git tag
      - name: Print changelog
        id: changelog
        run: |
          CHANGELOG=$(npx --yes @mastoj/md-changelog --from ${{ steps.tag_version.outputs.previous_tag }} --to ${{ steps.tag_version.outputs.new_tag }} --owner mastoj --repo branches --ghToken $GH_TOKEN)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Print change log
        run: echo "${{ steps.changelog.outputs.changelog }}"
      - name: Update Teams PR channel with links
        uses: satak/webrequest-action@v1.2.3
        with:
          url: ${{ secrets.TEAMS_PR_URL }}
          method: POST
          payload: >-
            {
              "type": "message",
              "attachments": [
                {
                  "contentType": "application/vnd.microsoft.card.adaptive",
                  "contentUrl": null,
                  "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.2",
                    "body": [
                      {
                        "type": "ColumnSet",
                        "spacing": "large",
                        "separator": true,
                        "columns": [
                          {
                            "width": "32px",
                            "items": [
                              {
                                "type": "Image",
                                "width": "32px",
                                "style": "person",
                                "horizontalAlignment": "center",
                                "url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                                "altText": "GitHub"
                              }
                            ]
                          },
                          {
                            "width": "stretch",
                            "items": [
                              {
                                "type": "TextBlock",
                                "text": "${{ toJson(steps.changelog.outputs.changelog) }}"
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
# echo "New version: ${{ steps.tag_version.outputs.new_version }}"
# git show ${{ steps.tag_version.outputs.new_version }}
# --pretty:'%s' 
# | grep -v 'Merge pull request'
# git log ${{ steps.tag_version.outputs.previous_version }}...${{ steps.tag_version.outputs.new_version }} --pretty:'%s' | grep -v 'Merge pull request'
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
