name: Create release

# This step triggers after the learner creates a new repository from the template
# This step sets STEP to 1
# This step closes <details id=0> and opens <details id=1>

# This will run every time we create push a commit to `main`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     main
  #   types:
  #     closed

permissions: write-all

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  get_pr_number:
    env:
      GH_TOKEN: ${{ github.token }}
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}    
      - name: Print changelog
        run: |
          echo "Changelog:"
          echo "Previous version: ${{ steps.tag_version.outputs.previous_version }}"
          echo "New version: ${{ steps.tag_version.outputs.new_version }}"
          echo "Changes:"
          git log v0.0.3...v0.0.4 --format:"%s" | grep -v "Merge pull request"
          git log ${{ steps.tag_version.outputs.previous_version }}...${{ steps.tag_version.outputs.new_version }} --format:\"%s\" | grep -v \"Merge pull request\"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
